---
title: "HW8_MandMs"
---

In this assignment, you'll be picking up where you left off with the M&Ms activity. You'll load the data and perform some basic statistical analysis. Follow the steps below to complete the assignment.

### Task 1: Load the tidyverse
library(tidyverse)


### Task 2: Load the M&Ms dataset from https://raw.githubusercontent.com/dwillis/jour405/refs/heads/main/data/mandms.csv
data <-read_csv("https://raw.githubusercontent.com/dwillis/jour405/refs/heads/main/data/mandms.csv")

### Task 3: Sample 5 rows of data from the dataset
set.seed(20)

sampled_data <- data |>
  slice_sample(n = 5)
  
sampled_data


### Task 4: Calculate the mean age and standard deviation of the sample, using either the blue or white number of M&Ms
sample_stats <- sampled_data |>
  summarise(
    mean_sample = mean(red),
    sd_sample = sd(red)
  )


### Task 5: Calculate the mean age and standard deviation of the population, using the same measure as in Task 4
population_stats <- data |>
  summarise(
    mean_population = mean(red),
    sd_population = sd(red)
  )

### Task 6: Compare the sample and population statistics

Compare the two sets of means and standard deviations. Are they similar?
The sample mean is 73.4 and is very close to the population mean 72.98. Despite this small difference, the sample deviation of 9.42 is a lot smaller than the population standard deviation of 16.46. This difference is caused by the small size of the sample. 

### Task 7: Describe the results

Write a few sentences about what you found in the data. What does this tell you about the M&Ms dataset and about the act of random sampling?
The results show that the sample stats are close to the population stats but of course are not exactly accurate. The sample mean is close to the population mean meaning that the sample I had was relatively accurate. However, the standard deviation has a strong difference because the sample size is so small. This proves that while samples can be helpful, for the M&Ms dataset, and all datasets, having a full population is more accurate. 


When finished, save your work, switch to GitHub Desktop, then add, commit and push your changes to GitHub and submit the URL of the notebook in ELMS.
