---
title: "final_project"
output: html_document
---
###Link to AI: 
https://chatgpt.com/share/69f0304d-aecc-83ea-a3ed-716d4fd2c445
### Updates:
Hi! So, I added my attempt to find out the "gap" in my data and basically answer "Are Black students represented in study abroad at the same rate they are enrolled in college? And is that gap shrinking over time?". My data and test ran okay, I used some of the skills such as mutate and lm that we learned in this course, however, my data isn't showing up. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(readxl)
url <- "https://opendoorsdata.org/wp-content/uploads/2025/11/OD25_US-Study-Abroad_Tables.xlsx"
download.file(url, destfile = "open_doors.xlsx", mode = "wb")
excel_sheets("open_doors.xlsx")
blackstudy_abroad <- read_excel("open_doors.xlsx", sheet = 2, skip = 3)
colnames(blackstudy_abroad) <- c("year", "total", "annual_change")
```

```{r, load}
url <- "https://opendoorsdata.org/wp-content/uploads/2025/11/OD25_US-Study-Abroad_Tables.xlsx"
download.file(url, destfile = "open_doors.xlsx", mode = "wb")
excel_sheets("open_doors.xlsx")
leading_institutions <- read_excel("open_doors.xlsx", sheet = 8)
```
```{r, load}
url <- "https://opendoorsdata.org/wp-content/uploads/2025/11/OD25_US-Study-Abroad_Tables.xlsx"
download.file(url, destfile = "open_doors.xlsx", mode = "wb")
excel_sheets("open_doors.xlsx")
top_locations <- read_excel("open_doors.xlsx", sheet = 5)
```

```{r, clean_up}
blackstudy_abroad_clean <- blackstudy_abroad %>%
  mutate(
    year = as.character(year),
    total = as.numeric(total),
    annual_change = as.numeric(annual_change)
  ) %>%
  filter(
    !is.na(year),
    year != "Year",
    !is.na(total)
  )
blackstudy_abroad_clean <- blackstudy_abroad_clean %>%
  mutate(year = factor(year, levels = year))
```

```{r, graph_data}
ggplot(blackstudy_abroad_clean, aes(x = year, y = total, group = 1)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(
    title = "U.S. Study Abroad Totals, 1985/86 - 2023/24",
    x = "Year",
    y = "Total Students"
  ) +
  scale_y_continuous(labels = scales::comma)
```
```{r, black_enrollment_data}
black_enrollment <- read_csv("/Users/savannahgrooms/Documents/table.csv", skip = 2)
```

```{r, clean_black_enrollment}
black_enrollment_clean <- black_enrollment |>
  rename(
    year = 1,
    black_enrollment_percent = 2
  ) |>
  mutate(
    year = as.character(year),
    black_enrollment_percent = as.numeric(black_enrollment_percent)
  ) |>
  filter(!is.na(year), !is.na(black_enrollment_percent))
```

```{r, test}
blackstudy_abroad_gap <- blackstudy_abroad_clean |>
  mutate(
    black_study_abroad_percent = total / sum(total) * 100
  )

combined_data <- full_join(
  blackstudy_abroad_for_gap,
  black_enrollment_clean,
  by = "year"
)

gap_data <- combined_data |>
  mutate(
    gap = black_enrollment_percent - black_study_abroad_percent
  )

```
